#!/usr/bin/php-cgi
<?php
// Simple CGI test script - Hello World

header("Content-Type: text/html");

$name = isset($_GET['name']) ? $_GET['name'] : 'World';

echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "<head><title>CGI PHP Test</title></head>\n";
echo "<body>\n";
echo "<h1>Hello, " . htmlspecialchars($name) . "!</h1>\n";
echo "<p>This response was generated by PHP-CGI</p>\n";
echo "<hr>\n";
echo "<p><strong>Request Method:</strong> " . $_SERVER['REQUEST_METHOD'] . "</p>\n";
echo "<p><strong>Query String:</strong> " . (isset($_SERVER['QUERY_STRING']) ? $_SERVER['QUERY_STRING'] : '(none)') . "</p>\n";
echo "<p><strong>Script Name:</strong> " . $_SERVER['SCRIPT_NAME'] . "</p>\n";
echo "</body>\n";
echo "</html>\n";
?>